<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE5\x02\x0A\x10helloworld.proto\x12\x17tondbad.test.helloworld\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"\x1D\x0A\x0AHelloReply\x12\x0F\x0A\x07message\x18\x01 \x01(\x092\xC1\x01\x0A\x07Greeter\x12V\x0A\x08SayHello\x12%.tondbad.test.helloworld.HelloRequest\x1A#.tondbad.test.helloworld.HelloReply\x12^\x0A\x0ESayHelloStream\x12%.tondbad.test.helloworld.HelloRequest\x1A#.tondbad.test.helloworld.HelloReply0\x01B/\xCA\x02,TondbadSwoole\\Tests\\Fixtures\\Grpc\\Helloworldb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

