<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/health/v1/health.proto

namespace GPBMetadata\Grpc\Health\V1;

class Health
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC5\x03\x0A\x1Bgrpc/health/v1/health.proto\x12\x0Egrpc.health.v1\"%\x0A\x12HealthCheckRequest\x12\x0F\x0A\x07service\x18\x01 \x01(\x09\"\x94\x01\x0A\x13HealthCheckResponse\x12A\x0A\x06status\x18\x01 \x01(\x0E21.grpc.health.v1.HealthCheckResponse.ServingStatus\":\x0A\x0DServingStatus\x12\x0B\x0A\x07UNKNOWN\x10\x00\x12\x0B\x0A\x07SERVING\x10\x01\x12\x0F\x0A\x0BNOT_SERVING\x10\x022\xAE\x01\x0A\x06Health\x12P\x0A\x05Check\x12\".grpc.health.v1.HealthCheckRequest\x1A#.grpc.health.v1.HealthCheckResponse\x12R\x0A\x05Watch\x12\".grpc.health.v1.HealthCheckRequest\x1A#.grpc.health.v1.HealthCheckResponse0\x01B\x1F\xCA\x02\x1CTondbadSwoole\\Grpc\\Health\\V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

