<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace TondbadSwoole\Grpc\Reflection\V1alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.reflection.v1alpha.ExtensionRequest</code>
 */
class ExtensionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string containing_type = 1;</code>
     */
    protected $containing_type = '';
    /**
     * Generated from protobuf field <code>int32 extension_number = 2;</code>
     */
    protected $extension_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $containing_type
     *     @type int $extension_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Reflection\V1Alpha\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string containing_type = 1;</code>
     * @return string
     */
    public function getContainingType()
    {
        return $this->containing_type;
    }

    /**
     * Generated from protobuf field <code>string containing_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContainingType($var)
    {
        GPBUtil::checkString($var, True);
        $this->containing_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 extension_number = 2;</code>
     * @return int
     */
    public function getExtensionNumber()
    {
        return $this->extension_number;
    }

    /**
     * Generated from protobuf field <code>int32 extension_number = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExtensionNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->extension_number = $var;

        return $this;
    }

}

