<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace TondbadSwoole\Grpc\Reflection\V1alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.reflection.v1alpha.ExtensionNumberResponse</code>
 */
class ExtensionNumberResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string base_type_name = 1;</code>
     */
    protected $base_type_name = '';
    /**
     * Generated from protobuf field <code>repeated int32 extension_number = 2;</code>
     */
    private $extension_number;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $base_type_name
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $extension_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Reflection\V1Alpha\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string base_type_name = 1;</code>
     * @return string
     */
    public function getBaseTypeName()
    {
        return $this->base_type_name;
    }

    /**
     * Generated from protobuf field <code>string base_type_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseTypeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->base_type_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 extension_number = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtensionNumber()
    {
        return $this->extension_number;
    }

    /**
     * Generated from protobuf field <code>repeated int32 extension_number = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtensionNumber($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->extension_number = $arr;

        return $this;
    }

}

