<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace TondbadSwoole\Grpc\Reflection\V1alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.reflection.v1alpha.FileDescriptorResponse</code>
 */
class FileDescriptorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1;</code>
     */
    private $file_descriptor_proto;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $file_descriptor_proto
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Reflection\V1Alpha\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFileDescriptorProto()
    {
        return $this->file_descriptor_proto;
    }

    /**
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFileDescriptorProto($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->file_descriptor_proto = $arr;

        return $this;
    }

}

