<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace TondbadSwoole\Grpc\Reflection\V1alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.reflection.v1alpha.ListServiceResponse</code>
 */
class ListServiceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    private $service;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\TondbadSwoole\Grpc\Reflection\V1alpha\ServiceResponse>|\Google\Protobuf\Internal\RepeatedField $service
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Reflection\V1Alpha\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     * @param array<\TondbadSwoole\Grpc\Reflection\V1alpha\ServiceResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setService($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TondbadSwoole\Grpc\Reflection\V1alpha\ServiceResponse::class);
        $this->service = $arr;

        return $this;
    }

}

