<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace TondbadSwoole\Grpc\Reflection\V1alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.reflection.v1alpha.ServerReflectionResponse</code>
 */
class ServerReflectionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string original_request = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $original_request = '';
    /**
     * Generated from protobuf field <code>string host = 2;</code>
     */
    protected $host = '';
    protected $message_response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $original_request
     *     @type string $host
     *     @type \TondbadSwoole\Grpc\Reflection\V1alpha\ListServiceResponse $list_services_response
     *     @type \TondbadSwoole\Grpc\Reflection\V1alpha\FileDescriptorResponse $file_descriptor_response
     *     @type \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionNumberResponse $all_extension_numbers_response
     *     @type \TondbadSwoole\Grpc\Reflection\V1alpha\ErrorResponse $error_response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Reflection\V1Alpha\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string original_request = 1 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getOriginalRequest()
    {
        if ($this->original_request !== '') {
            @trigger_error('original_request is deprecated.', E_USER_DEPRECATED);
        }
        return $this->original_request;
    }

    /**
     * Generated from protobuf field <code>string original_request = 1 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setOriginalRequest($var)
    {
        @trigger_error('original_request is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->original_request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host = 2;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 3;</code>
     * @return \TondbadSwoole\Grpc\Reflection\V1alpha\ListServiceResponse|null
     */
    public function getListServicesResponse()
    {
        return $this->readOneof(3);
    }

    public function hasListServicesResponse()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 3;</code>
     * @param \TondbadSwoole\Grpc\Reflection\V1alpha\ListServiceResponse $var
     * @return $this
     */
    public function setListServicesResponse($var)
    {
        GPBUtil::checkMessage($var, \TondbadSwoole\Grpc\Reflection\V1alpha\ListServiceResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @return \TondbadSwoole\Grpc\Reflection\V1alpha\FileDescriptorResponse|null
     */
    public function getFileDescriptorResponse()
    {
        return $this->readOneof(4);
    }

    public function hasFileDescriptorResponse()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @param \TondbadSwoole\Grpc\Reflection\V1alpha\FileDescriptorResponse $var
     * @return $this
     */
    public function setFileDescriptorResponse($var)
    {
        GPBUtil::checkMessage($var, \TondbadSwoole\Grpc\Reflection\V1alpha\FileDescriptorResponse::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @return \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionNumberResponse|null
     */
    public function getAllExtensionNumbersResponse()
    {
        return $this->readOneof(5);
    }

    public function hasAllExtensionNumbersResponse()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @param \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionNumberResponse $var
     * @return $this
     */
    public function setAllExtensionNumbersResponse($var)
    {
        GPBUtil::checkMessage($var, \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionNumberResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 6;</code>
     * @return \TondbadSwoole\Grpc\Reflection\V1alpha\ErrorResponse|null
     */
    public function getErrorResponse()
    {
        return $this->readOneof(6);
    }

    public function hasErrorResponse()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 6;</code>
     * @param \TondbadSwoole\Grpc\Reflection\V1alpha\ErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var)
    {
        GPBUtil::checkMessage($var, \TondbadSwoole\Grpc\Reflection\V1alpha\ErrorResponse::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessageResponse()
    {
        return $this->whichOneof("message_response");
    }

}

