<?php

declare(strict_types=1);
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace TondbadSwoole\Grpc\Reflection\V1alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.reflection.v1alpha.ServerReflectionRequest</code>
 */
class ServerReflectionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string host = 1;</code>
     */
    protected $host = '';
    /**
     * Generated from protobuf field <code>string original_request = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $original_request = '';
    protected $message_request;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *     @type string $original_request
     *     @type string $list_services
     *     @type \TondbadSwoole\Grpc\Reflection\V1alpha\FileRequest $file_by_filename
     *     @type string $file_containing_symbol
     *     @type \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionRequest $file_containing_extension
     *     @type string $all_extension_numbers_of_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Reflection\V1Alpha\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string original_request = 2 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getOriginalRequest()
    {
        if ($this->original_request !== '') {
            @trigger_error('original_request is deprecated.', E_USER_DEPRECATED);
        }
        return $this->original_request;
    }

    /**
     * Generated from protobuf field <code>string original_request = 2 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setOriginalRequest($var)
    {
        @trigger_error('original_request is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->original_request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string list_services = 3;</code>
     * @return string
     */
    public function getListServices()
    {
        return $this->readOneof(3);
    }

    public function hasListServices()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string list_services = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setListServices($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.FileRequest file_by_filename = 4;</code>
     * @return \TondbadSwoole\Grpc\Reflection\V1alpha\FileRequest|null
     */
    public function getFileByFilename()
    {
        return $this->readOneof(4);
    }

    public function hasFileByFilename()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.FileRequest file_by_filename = 4;</code>
     * @param \TondbadSwoole\Grpc\Reflection\V1alpha\FileRequest $var
     * @return $this
     */
    public function setFileByFilename($var)
    {
        GPBUtil::checkMessage($var, \TondbadSwoole\Grpc\Reflection\V1alpha\FileRequest::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string file_containing_symbol = 5;</code>
     * @return string
     */
    public function getFileContainingSymbol()
    {
        return $this->readOneof(5);
    }

    public function hasFileContainingSymbol()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>string file_containing_symbol = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFileContainingSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 6;</code>
     * @return \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionRequest|null
     */
    public function getFileContainingExtension()
    {
        return $this->readOneof(6);
    }

    public function hasFileContainingExtension()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 6;</code>
     * @param \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionRequest $var
     * @return $this
     */
    public function setFileContainingExtension($var)
    {
        GPBUtil::checkMessage($var, \TondbadSwoole\Grpc\Reflection\V1alpha\ExtensionRequest::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string all_extension_numbers_of_type = 7;</code>
     * @return string
     */
    public function getAllExtensionNumbersOfType()
    {
        return $this->readOneof(7);
    }

    public function hasAllExtensionNumbersOfType()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>string all_extension_numbers_of_type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAllExtensionNumbersOfType($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessageRequest()
    {
        return $this->whichOneof("message_request");
    }

}

