<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example/error.proto

namespace GPBMetadata\Example;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ai\x0A\x13example/error.proto\x12\x0ETondbadExample\":\x0A\x0DErrorResponse\x12\x15\x0A\x0Derror_message\x18\x01 \x01(\x09\x12\x12\x0A\x0Aerror_code\x18\x02 \x01(\x05b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

