<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example/greeting.proto

namespace GPBMetadata\Example;

class Greeting
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xCC\x01\x0A\x16example/greeting.proto\x12\x0ETondbadExample\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\" \x0A\x0DHelloResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x092Z\x0A\x0FGreetingService\x12G\x0A\x08SayHello\x12\x1C.TondbadExample.HelloRequest\x1A\x1D.TondbadExample.HelloResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

